[package]
name = "use-cursor"
description = "Models opaque cursors and before, after, next, and previous cursor slots without assuming serialization or secrecy."
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-cursor"
keywords = ["cursorapi"]
categories = ["data-structures", "development-tools", "web-programming"]

[lints]
workspace = true